<?php

function reverse_pickup_menu() {
  $items = array();

  $items['order-receive-import'] = array(
    'title' => ' Order Receive Importer',
    'description' => ' Order Receive Importer',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('order_receive_import_form'),
    'access arguments' => array('Reverse Pickup'),
    'file' => 'form/order_receive_import.inc',
  );
  return $items;
}

/**
 * Service for reverse pickup
 */
function reverse_pickup_services_resources() {
  $reverse_pickup_resource = array(
    '#api_version' => 3002,
  );
    $reverse_pickup_resource = array(
    'order-receive' => array(
      'actions' => array(
        'order-receive-api' => array(
          'help' => 'Order',
          'callback' => 'order_receive_data_callback',
          'args' => array(
            array(
              'name' => 'data',
              'type' => 'array',
              'description' => 'Post data',
              'source' => 'data',
              'optional' => TRUE,
            )
           ),
            'file' => array(
              'type' => 'inc',
              'module' => 'reverse_pickup',
              'name' => 'includes/order_receive_data'
            ),
            'access arguments' => array('Order Receive API'),
          ),
        ),
      ),
  );
  return $reverse_pickup_resource;
}

/**
 * permission
 */
function reverse_pickup_permission() {

  return array(
    'Reverse Pickup' => array(
      'title' => t('Reverse Pickup'),
      'description' => t('Reverse Pickup')
    ),
    'Order Receive API' => array(
      'title' => t('Order Receive API'),
      'description' => t('Order Receive API')
    )   
  );
}


/**
 * Implements of hook_views_api().
 */
function reverse_pickup_views_api() {
   return array(
     'api' => 3,
     'path' => drupal_get_path('module', 'reverse_pickup') . '/views'
   );
}

function get_order_qty_from_bill_sku($bill_no, $sku, $distributor_id) {
    $query = db_select('custom_billing_data', 'cb');
    $query->condition('cb.bill_number', $bill_no, '=');
    $query->condition('cb.sku7_code', $sku, '=');
    $query->condition('cb.distributor_id', $distributor_id, '=');
    $query->fields('cb', array('Sum_of_TOTAL_SALES_QTY'));
    $delivered_qty = $query->execute()->fetchField();
    return $delivered_qty;
}

function get_distributor_by_title($title,$type){
  $query = db_select('node', 'n');
  $query->condition('n.type', $type);
  $query->condition('n.title', $title);
  $query->fields('n', array('uid'));
  $result = $query->execute()->fetchField();
  return $result;
}


function validate_content_title($title,$type){
  $query = db_select('node', 'n');
  $query->condition('n.type', $type);
  $query->condition('n.title', $title);
  $query->fields('n', array('title'));
  $result = $query->execute()->fetchField();
  return $result;
}

function check_bill_exists_with_party($title, $type, $party) {
    $query1 = db_select('node', 'n');
    $query1->condition('n.type', $type);
    $query1->condition('n.title', $title);
    $query1->fields('n', array('nid'));
    if ($party) {
        $query1->join('field_data_field_sales_party_code', 'd', 'd.entity_id = n.nid');
        $query1->condition('d.field_sales_party_code_value', $party);
    }
    $nid = $query1->execute()->fetchField();
    return $nid;
}

//will use this function if we have to check delivered qty
function get_delivered_qty_from_bill_sku($bill_no, $sku) {
    $query = db_select('dispatch_planning_api_data', 'ad');
    $query->join('dispatch_planning_item_details', 'itd', 'itd.trip_bill_reference = ad.id');
    $query->condition('ad.bill_number', $bill_no, '=');
    $query->condition('itd.sku_code', $sku, '=');
    $query->fields('itd', array('farey_delivered_qty'));
    $delivered_qty = $query->execute()->fetchField();
  return $delivered_qty;
}