<?php

function reverse_pickup_menu() {
  $items = array();

  $items['order-receive-import'] = array(
    'title' => ' Order Receive Importer',
    'description' => ' Order Receive Importer',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('order_receive_import_form'),
    'access arguments' => array('Reverse Pickup'),
    'file' => 'form/order_receive_import.inc',
  );
  $items['order-receive-data-create'] = array(
    'title' => '',
    'page callback' => 'order_receive_data_create_callback',
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM,
    'file' => 'includes/order_receive_data_create.inc',
  );
  return $items;
}

/**
 * Service for reverse pickup
 */
function reverse_pickup_services_resources() {
  $reverse_pickup_resource = array(
    '#api_version' => 3002,
  );
    $reverse_pickup_resource = array(
    'order-receive' => array(
      'actions' => array(
        'order-receive-api' => array(
          'help' => 'Order',
          'callback' => 'order_receive_data_callback',
          'args' => array(
            array(
              'name' => 'data',
              'type' => 'array',
              'description' => 'Post data',
              'source' => 'data',
              'optional' => TRUE,
            )
           ),
            'file' => array(
              'type' => 'inc',
              'module' => 'reverse_pickup',
              'name' => 'includes/order_receive_data'
            ),
            'access arguments' => array('Order Receive API'),
          ),
        ),
      ),
  );
  return $reverse_pickup_resource;
}

/**
 * permission
 */
function reverse_pickup_permission() {

  return array(
    'Reverse Pickup' => array(
      'title' => t('Reverse Pickup'),
      'description' => t('Reverse Pickup')
    ),
    'Order Receive API' => array(
      'title' => t('Order Receive API'),
      'description' => t('Order Receive API')
    )   
  );
}


/**
 * Implements of hook_views_api().
 */
function reverse_pickup_views_api() {
   return array(
     'api' => 3,
     'path' => drupal_get_path('module', 'reverse_pickup') . '/views'
   );
}

function get_order_qty_from_bill_sku($bill_no, $sku, $distributor_id) {
    $query = db_select('custom_billing_data', 'cb');
    $query->condition('cb.bill_number', $bill_no, '=');
    $query->condition('cb.sku7_code', $sku, '=');
    $query->condition('cb.distributor_id', $distributor_id, '=');
    $query->fields('cb', array('Sum_of_TOTAL_SALES_QTY'));
    $delivered_qty = $query->execute()->fetchField();
    return $delivered_qty;
}

function get_distributor_by_title($title,$type){
  $query = db_select('node', 'n');
  $query->condition('n.type', $type);
  $query->condition('n.title', $title);
  $query->fields('n', array('uid'));
  $result = $query->execute()->fetchField();
  return $result;
}


function validate_content_title($title,$type){
  $query = db_select('node', 'n');
  $query->condition('n.type', $type);
  $query->condition('n.title', $title);
  $query->fields('n', array('title'));
  $result = $query->execute()->fetchField();
  return $result;
}

function check_bill_exists_with_party($title, $type, $party) {
    $query1 = db_select('node', 'n');
    $query1->condition('n.type', $type);
    $query1->condition('n.title', $title);
    $query1->fields('n', array('nid'));
    if ($party) {
        $query1->join('field_data_field_sales_party_code', 'd', 'd.entity_id = n.nid');
        $query1->condition('d.field_sales_party_code_value', $party);
    }
    $nid = $query1->execute()->fetchField();
    return $nid;
}

//will use this function if we have to check delivered qty
function get_delivered_qty_from_bill_sku($bill_no, $sku, $distributor_id) {
    $query = db_select('dispatch_planning_api_data', 'ad');
    $query->join('dispatch_planning_item_details', 'itd', 'itd.trip_bill_reference = ad.id');
    $query->condition('ad.bill_number', $bill_no, '=');
    $query->condition('ad.distributor_id', $distributor_id, '=');
    $query->condition('itd.sku_code', $sku, '=');
    $query->fields('itd', array('res_sku_actual_quantity1'));
    $delivered_qty = $query->execute()->fetchField();
  return $delivered_qty;
}

function check_child_order_in_order_receive($child_order_id, $distributor_id) {
    $query = db_select('order_receive_data', 'ord');
    $query->condition('ord.child_order_id', $child_order_id, '=');
    $query->condition('ord.distributor_id', $distributor_id, '=');
    $query->fields('ord', array('child_order_id'));
    $res = $query->execute()->fetchField();
  return $res;
}

function check_child_order_in_sales_register($child_order_id, $distributor_id) {
    $query = db_select('field_data_field_outlet_order_no', 'fco');
    $query->join('node', 'n', 'fco.entity_id = n.nid');
    $query->condition('fco.bundle', 'sales_register_data', '=');
    $query->condition('fco.field_outlet_order_no_value', $child_order_id, '=');
    $query->condition('n.uid', $distributor_id, '=');
    $query->fields('fco', array('field_outlet_order_no_value'));
    $res = $query->execute()->fetchField();
  return $res;
}

function get_upc_by_skus($sku7_code) {
    $query = db_select('node', 'n');
    $query->condition('n.type', 'sku7_code_master');
    $query->condition('n.title', $sku7_code);
    $query->leftjoin('field_data_field_unit_case_units_', 'uc', 'uc.entity_id = n.nid');
    $query->addField('uc', 'field_unit_case_units__value', 'upc');
    $res = $query->execute()->fetchField();
    return $res;
}