<?php

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


function get_node_title_using_nid($nid) {
   if (!empty($nid)) {
    $query = db_select('node', 'n');
    $query->condition('n.nid', $nid);
    $query->fields('n', array('title'));
    $title = $query->execute()->fetchField();
   }
   return $title;
}

function lcd_retailer_master_api_node_presave($node) {
    $retailer_masters = array('outlet_master', 'area_code_master', 'hul_code_master');
    if (in_array($node->type, $retailer_masters)) {
        $hul_code =  get_node_title_using_nid($node->field_hul_code_reference[LANGUAGE_NONE][0]['nid']);
         if ($node->type == 'outlet_master') {
            $api_data['type'] = 'outlet_master';  
            $api_data['title'] = $node->title;  
            $api_data['field_beat_name'] = $node->field_beat_name[LANGUAGE_NONE][0]['value'] ;  
            $api_data['field_hul_code_ref'] =  $hul_code ;    
            $api_data['field_outlet_channel'] =  $node->field_channel[LANGUAGE_NONE][0]['value'];  
            $api_data['field_party_name'] = $node->field_party_name[LANGUAGE_NONE][0]['value'] ;  
            $api_data['field_pl_group'] = $node->field_pl_group[LANGUAGE_NONE][0]['value'];  
            $api_data['field_sales_day'] = $node->field_sales_day[LANGUAGE_NONE][0]['value'];    
            $api_data['field_salesman'] = $node->field_salesman[LANGUAGE_NONE][0]['value'];      
            $api_data['field_salesman_code'] = $node->field_salesman_code[LANGUAGE_NONE][0]['value']; 
        }
        if ($node->type == 'hul_code_master') {
            $area_code =  get_node_title_using_nid($node->field_area_code[LANGUAGE_NONE][0]['nid']);
            if (empty($area_code)) {
                $area_code = 0;
            }
            $api_data['type'] = 'hul_code_master';  
            $api_data['hul_code'] = $node->title;  
            $api_data['field_hul_address'] = $node->field_hul_address[LANGUAGE_NONE][0]['value'] ;  
            $api_data['field_hul_area'] =  $node->field_hul_area[LANGUAGE_NONE][0]['value'] ;
            $api_data['field_area_code'] =  $area_code ;
            $api_data['field_hul_lat'] =  $node->field_hul_lat[LANGUAGE_NONE][0]['value'];  
            $api_data['field_hul_long'] = $node->field_hul_long[LANGUAGE_NONE][0]['value'] ;  
            $api_data['field_hul_phone_no'] = $node->field_hul_phone_no[LANGUAGE_NONE][0]['value'];  
            $api_data['field_hul_street'] = $node->field_hul_street[LANGUAGE_NONE][0]['value'];    
            $api_data['field_hul_sub_area'] = $node->field_hul_sub_area[LANGUAGE_NONE][0]['value'];      
            $api_data['field_party_name'] = $node->field_party_name[LANGUAGE_NONE][0]['value']; 
            $api_data['field_sms_required'] = $node->field_sms_required[LANGUAGE_NONE][0]['value']; 
        }
        
        if ($node->type == 'area_code_master') {
            $sub_area_code =  get_node_title_using_nid($node->field_linked_area_code[LANGUAGE_NONE][0]['nid']);
            if (empty($sub_area_code)) {
                $sub_area_code = 0;
            }
            $api_data['type'] = 'area_code_master';  
            $api_data['area_code'] = $node->title;  
            $api_data['sub_area_code'] = $sub_area_code ;  
        }
        $data = json_encode($api_data);

        //dsm($node,'node');
       // dsm($api_data);
       // $authorization = 'bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ODgzOWY4ZjYyZmQyMzkzMGE4NjQwYjEiLCJpYXQiOjE1MDQ2Nzg4NTl9.AzJLVp6HDk6lbXCWxI1T8Y7US6R0panNjkY5B-pkdqg';
        $request_headers = array('Content-Type' => 'application/json', 'Authorization' => $authorization);
        $api_url = variable_get('retailer_api_master_url', 'http://dev-lak.leanbox.in/retailer_master/update_retailer_master_data');
        $api_options = array('headers' => $request_headers, 'method' => 'POST', 'data' => $data);
        $response_data = drupal_http_request($api_url, $api_options);
        //dpm($response_data,'API RESPONSE');
        //$response_data = json_decode($response_data->data);
    }
}
