<?php

/**
 * This module is to show the live van tracking from FarEye
 */

/**
 * Implements hook_menu
 */

function mrc_live_tracking_menu() {
  $items['van-live-track'] = array(
    'title' => 'Real-time Van Tracking',
    'page callback' => 'van_live_tracking',
    'access arguments' => array('live van tracking'),
    'type' => MENU_CALLBACK,
    'file' => 'includes/mrc_live_tracking.inc'    
  );
  $items['van-live-track-history'] = array(
    'title' => 'Real-time Van Tracking History',
    'page callback' => 'van_live_tracking_history',
    'access arguments' => array('live van tracking'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'includes/mrc_live_tracking_history.inc'    
  );
   $items['van-live-track-history/allvan'] = array(
    'title' => 'All Vans',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => 0,
  );
  $items['van-live-track-history/vanwise'] = array(
    'title' => 'Van Wise',
    'page callback' => 'van_live_tracking_history_vanwise',
    'access arguments' => array('live van tracking'),
    'type' => MENU_LOCAL_TASK,
    'weight' => 1,
    'file' => 'includes/mrc_live_tracking_history_vanwise.inc'    
  );

  return $items;
}
/**
 * 
 * @return type
 */
function mrc_live_tracking_permission() {
  return array(
    'live van tracking' => array(
      'title' => t('live van tracking'),
      'description' => t('live van tracking')
    ),
  );
}
/**
 * Implements of hook_views_api().
 */
function mrc_live_tracking_views_api() {
  return array(
    'api' => 3,
    'path' => drupal_get_path('module', 'mrc_live_tracking') . '/views'
  );
}

function mrc_live_tracking_services_resources() {
  $resource = array(
    '#api_version' => 3002
  );
  $resource = array(
    'live-tracking' => array(
      'actions' => array(
        'van-api-data' => array(
          'help' => 'Get live tracking Data',
          'callback' => 'get_live_tracking_van_api_data',
          'args' => array(
            array(
              'name' => 'data',
              'type' => 'array',
              'description' => 'Post data',
              'source' => 'data',
              'optional' => TRUE,
            ),
          ),
          'file' => array(
            'type' => 'inc',
            'module' => 'mrc_live_tracking',
            'name' => 'includes/mrc_live_tracking_api'
          ),
          'access arguments' => array('services_access_farey_api'),
        ),
      ),
    ),
  );
  return $resource;
}
