<?php
function custom_order_box_id_menu() {
  $items = array();
  
  $items['custom-order-box-id-import'] = array(
    'title' => 'Import Custom Order Box Id',
    'description' => 'Import Custom Order Box Id',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('custom_order_box_id_upload_form'),
    'access arguments' => true,
    'file' => 'form/custom_order_box_id.inc',
  ); 
  return $items;
}
