<?php

/**
 * Files containing list of custom blocks
 * having graph data integrated using google chart
 */

/**
 * Implements hook_menu
 */
function leanbox_dashboard_menu() {
  $items = array();

  $items['dashboard'] = array(
    'page callback' => 'leanbox_dashboard_listing_page',
    'access arguments' => array('Distributor Upload File'),
    'type' => MENU_NORMAL_ITEM,
  );

  $categories = array(
    'Progress' => 'Progress',
    'Metrics' => 'Metrics',
    'Productivity' => 'Productivity',
    'ota' => 'On-Time Adherence',
  );

  $items['dashboard/Progress'] = array(
    'title' => 'Progress',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => 0,
    'access arguments' => array('Distributor Upload File'),
  );

  $d = 1;
  foreach ($categories as $k => $v) {
    $items['dashboard/' . $k] = array(
      'title' => $v,
      'access arguments' => array('Distributor Upload File'),
      'type' => MENU_LOCAL_TASK,
      'weight' => $d++,
    );
  }

  // Upload form for sales register data
  $items['area-hook-group/import'] = array(
    'title' => 'Area Hook Group',
    'description' => 'Import Area Hook Group',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('leanbox_dashboard_area_hook_group_form'),
    'access arguments' => array('Distributor Upload File'),
    'file' => 'includes/leanbox_dashboard_areahookgroup.inc',
  );

  $items['area-hook-group-confirm/%'] = array(
    'title' => 'Area Hook Group Confirm Table',
    'description' => 'Area Hook Group Confirm Table',
    'page callback' => 'leanbox_dashboard_area_hook_group_confirm_content',
    'page arguments' => array(1),
    'access arguments' => array('Distributor Upload File'),
    'file' => 'includes/leanbox_dashboard_areahookgroup.inc',
  );

  // when confirm is clicked
  $items['area-hook-group-confirm/create_content/%'] = array(
    'title' => 'Area Hook Group',
    'description' => 'Area Hook Group create Update node of Area Hook Group',
    'page callback' => 'leanbox_dashboard_area_hook_group_create_confirm_content',
    'page arguments' => array(2),
    'access arguments' => array('Distributor Upload File'),
    'file' => 'includes/leanbox_dashboard_areahookgroup.inc',
  );

  // when discard is clicked
  $items['area-hook-group-discard/%'] = array(
    'title' => 'Area Hook Group delete',
    'description' => 'deletes area hook group data',
    'page callback' => 'leanbox_dashboard_area_hook_group_discard_data',
    'page arguments' => array(1),
    'access arguments' => array('Distributor Upload File'),
    'file' => 'includes/leanbox_dashboard_areahookgroup.inc',
  );


  $items['area-hook-grouping'] = array(
    'title' => 'Area Hook Grouping',
    'page callback' => 'leanbox_dashboard_area_hook_grouping_callback',
    'access arguments' => array('Distributor Upload File'),
    'file path' => drupal_get_path('module', 'leanbox_dashboard'),
    'file' => '/includes/leanbox_dashboard_areahook.inc',
  );
  $items['area-hook-grouping-download'] = array(
    'title' => 'Area Hook Grouping Download',
    'page callback' => 'leanbox_dashboard_area_hook_grouping_download',
    'access arguments' => array('Distributor Upload File'),
    'file path' => drupal_get_path('module', 'leanbox_dashboard'),
    'file' => '/includes/leanbox_dashboard_areahook.inc',
  );
  $items['chart-daterange-filter'] = array(
    'title' => 'Party Packing',
    'page callback' => 'party_packing_filter_callback',
    'access arguments' => array('Distributor Upload File'),
  );
  $items['leanbox-chart-details/%'] = array(
    'title ' => '',
    'page callback' => 'leanbox_dashboard_chart_details_callback',
    'page arguments' => array(1),
    'access arguments' => array('Distributor Upload File'),
    'file path' => drupal_get_path('module', 'leanbox_dashboard'),
    'file' => '/includes/leanbox_dashboard_chart.inc',
  );

  return $items;
}

/**
 * Callback function for dashboard page
 * @return string
 */
function leanbox_dashboard_listing_page() {
  return '';
}

/**
 * 
 */
function party_packing_filter_callback() {
  module_load_include('inc', 'leanbox_dashboard', 'includes/leanbox_dashboard');
  $start_date = $end_date = '';
  $activity_type = $_POST['activity_type'];
  $ajax_type = '';

  if (isset($_POST['start_date'])) {
    $start_date = $_POST['start_date'];
  }
  if (isset($_POST['end_date'])) {
    $end_date = $_POST['end_date'];
  }
//  if ($activity_type == 'otif') {
//    $activity_type = 'otif_ajax';
//    $output_data = leanbox_dashboard_gauge_chart_query_details($activity_type, $start_date, $end_date);
//  }
//  else {
//    
//    if ($activity_type == 'party_packing_productivity') {
//      $ajax_type = 'party_packing_ajax';
//    }
//    else if ($activity_type == 'picking_productivity') {
//      $ajax_type = 'picking_ajax';
//    }
//    else if ($activity_type == 'bill_pendency') {
//      $ajax_type = 'bill_pendency_ajax';
//    }
//
//    $output_data = leanbox_dashboard_chart_query_details($activity_type, $start_date, $end_date, $ajax_type);
//  }
  switch ($activity_type) {
    case 'otif' :
      $activity_type = 'otif_ajax';
      $output_data = leanbox_dashboard_gauge_chart_query_details($activity_type, $start_date, $end_date);
      break;

    case 'party_packing_productivity' :
      $ajax_type = 'party_packing_ajax';
      $output_data = leanbox_dashboard_chart_query_details($activity_type, $start_date, $end_date, $ajax_type);
      break;

    case 'picking_productivity' :
      $ajax_type = 'picking_ajax';
      $output_data = leanbox_dashboard_chart_query_details($activity_type, $start_date, $end_date, $ajax_type);
      break;

    case 'bill_pendency' :
      $ajax_type = 'bill_pendency_ajax';
      $output_data = leanbox_dashboard_chart_query_details($activity_type, $start_date, $end_date, $ajax_type);
      break;

    case 'otif_trends' :
      $activity_type = 'otif_ajax';
      $output_data = leanbox_dashboard_otif_trends_chart_query_details($activity_type, $start_date, $end_date);
      break;

    default:
      $output_data = leanbox_dashboard_chart_query_details($activity_type, $start_date, $end_date, $ajax_type);
  }
  
  drupal_json_output($output_data);
}

/**
 * 
 */
function leanbox_dashboard_block_info() {
  $blocks['party_packing'] = array(
    'info' => t('Party Packing Chart'),
    'cache' => DRUPAL_NO_CACHE,
  );
  $blocks['picking'] = array(
    'info' => t('Picking Loose Chart'),
    'cache' => DRUPAL_NO_CACHE,
  );
  $blocks['picking_bulk'] = array(
    'info' => t('Picking Bulk Chart'),
    'cache' => DRUPAL_NO_CACHE,
  );
  $blocks['unloading'] = array(
    'info' => t('Unloading Chart'),
    'cache' => DRUPAL_NO_CACHE,
  );
  $blocks['delivery'] = array(
    'info' => t('Sales Delivery Chart'),
    'cache' => DRUPAL_NO_CACHE,
  );
  $blocks['otif'] = array(
    'info' => t('Otif'),
    'cache' => DRUPAL_NO_CACHE,
  );
  $blocks['party_packing_productivity'] = array(
    'info' => t('Party Packing Productivity'),
    'cache' => DRUPAL_NO_CACHE,
  );
  $blocks['picking_productivity'] = array(
    'info' => t('Picking Productivity'),
    'cache' => DRUPAL_NO_CACHE,
  );
  $blocks['bills_per_person'] = array(
    'info' => t('Bills Delivered Per Person'),
    'cache' => DRUPAL_NO_CACHE,
  );
  $blocks['bills_per_van'] = array(
    'info' => t('Bills Delivered Per Van'),
    'cache' => DRUPAL_NO_CACHE,
  );
  $blocks['pp_ota'] = array(
    'info' => t('PP On Time Adherence'),
    'cache' => DRUPAL_NO_CACHE,
  );
  $blocks['picking_ota'] = array(
    'info' => t('Picking On Time Adherence'),
    'cache' => DRUPAL_NO_CACHE,
  );
  $blocks['unloading_ota'] = array(
    'info' => t('Unloading On Time Adherence'),
    'cache' => DRUPAL_NO_CACHE,
  );
  $blocks['dispatch_ota'] = array(
    'info' => t('Dispatch On Time Adherence'),
    'cache' => DRUPAL_NO_CACHE,
  );
  $blocks['outlet_status'] = array(
    'info' => t('Outlet Status'),
    'cache' => DRUPAL_NO_CACHE,
  );
  $blocks['bill_pendency'] = array(
    'info' => t('Bill Pendency'),
    'cache' => DRUPAL_NO_CACHE,
  );
  $blocks['otif_trends'] = array(
    'info' => t('Otif Day Wise Trends'),
    'cache' => DRUPAL_NO_CACHE,
  );
  return $blocks;
}

/**
 * Implements hook_block_view
 * 
 */
function leanbox_dashboard_block_view($delta = '') {
  // Include leanbox_dashboard inc file
  module_load_include('inc', 'leanbox_dashboard', 'includes/leanbox_dashboard');
  $area_definition = array(
    'width' => 340,
    'height' => 300,
    'ch_left' => 50,
    'ch_top' => 50,
    'ch_width' => 290,
    'ch_height' => 200,
  );
  switch ($delta) {
    case 'party_packing':

      if (arg(1) == 'party_packing') {
        $area_definition = array(
          'width' => 700,
          'height' => 400,
          'ch_left' => 80,
          'ch_top' => 50,
          'ch_width' => 500,
          'ch_height' => 250,
        );
      }

      $loading_date = date('d-m-Y');
      $block['subject'] = "Party Packing Van Progress ($loading_date Loading)";
      $data = leanbox_dashboard_chart_query_details('party_packing');
      $filter_form = drupal_render(drupal_get_form('leanbox_dashboard_chart_filter_partypack_form'));
      $block['content'] = array(
        '#markup' => theme('leanbox_dashboard', array('data' => $filter_form)),
        '#attached' => array(
          'js' => array(
            array(
              'type' => 'external',
              'data' => 'https://www.gstatic.com/charts/loader.js'
            ),
            drupal_get_path('module', 'leanbox_dashboard') . '/js/leanbox_dashboard_partypackingchart.js',
            array(
              'data' => array('leanbox_dashboard' => array('party_packing' => $data, 'area_definition' => $area_definition)),
              'type' => 'setting'
            ),
          ),
        ),
      );
      break;

    case 'picking':

      if (arg(1) == 'picking') {
        $area_definition = array(
          'width' => 700,
          'height' => 400,
          'ch_left' => 80,
          'ch_top' => 50,
          'ch_width' => 500,
          'ch_height' => 250,
        );
      }
      $loading_date = date('d-m-Y');
      $block['subject'] = "Picking Progress Task Loose ($loading_date Loading)";
      $data = leanbox_dashboard_chart_query_details('picking');

      $filter_form = drupal_render(drupal_get_form('leanbox_dashboard_chart_filter_picking_form'));
      $block['content'] = array(
        '#markup' => theme('leanbox_dashboard', array('data' => $filter_form)),
        '#attached' => array(
          'js' => array(
            array(
              'type' => 'external',
              'data' => 'https://www.gstatic.com/charts/loader.js'
            ),
            drupal_get_path('module', 'leanbox_dashboard') . '/js/leanbox_dashboard_pickingchart.js',
            array(
              'data' => array('leanbox_dashboard' => array('picking' => $data, 'area_definition' => $area_definition)),
              'type' => 'setting'
            ),
          ),
        ),
      );
      break;

    case 'picking_bulk':

      if (arg(1) == 'picking_bulk') {
        $area_definition = array(
          'width' => 700,
          'height' => 400,
          'ch_left' => 80,
          'ch_top' => 50,
          'ch_width' => 500,
          'ch_height' => 250,
        );
      }
      $loading_date = date('d-m-Y');
      $block['subject'] = "Picking Progress Task Bulk ($loading_date Loading)";
      $data = leanbox_dashboard_chart_query_details('picking_bulk');

      $filter_form = drupal_render(drupal_get_form('leanbox_dashboard_chart_filter_picking_bulk_form'));
      $block['content'] = array(
        '#markup' => theme('leanbox_dashboard', array('data' => $filter_form)),
        '#attached' => array(
          'js' => array(
            array(
              'type' => 'external',
              'data' => 'https://www.gstatic.com/charts/loader.js'
            ),
            drupal_get_path('module', 'leanbox_dashboard') . '/js/leanbox_dashboard_pickingbulkchart.js',
            array(
              'data' => array('leanbox_dashboard' => array('picking_bulk' => $data, 'area_definition' => $area_definition)),
              'type' => 'setting'
            ),
          ),
        ),
      );
      break;

    case 'unloading':

      if (arg(1) == 'unloading') {
        $area_definition = array(
          'width' => 700,
          'height' => 400,
          'ch_left' => 80,
          'ch_top' => 50,
          'ch_width' => 500,
          'ch_height' => 250,
        );
      }
      $loading_date = date('d-m-Y');
      $block['subject'] = "Unloading Progress ($loading_date Invoice)";
      $data = leanbox_dashboard_chart_query_details('unloading');

      $filter_form = drupal_render(drupal_get_form('leanbox_dashboard_chart_filter_unloading_form'));
      $block['content'] = array(
        '#markup' => theme('leanbox_dashboard', array('data' => $filter_form)),
        '#attached' => array(
          'js' => array(
            array(
              'type' => 'external',
              'data' => 'https://www.gstatic.com/charts/loader.js'
            ),
            drupal_get_path('module', 'leanbox_dashboard') . '/js/leanbox_dashboard_unloading.js',
            array(
              'data' => array('leanbox_dashboard' => array('unloading' => $data, 'area_definition' => $area_definition)),
              'type' => 'setting'
            ),
          ),
        ),
      );
      break;

    case 'delivery':

      if (arg(1) == 'delivery') {
        $area_definition = array(
          'width' => 700,
          'height' => 400,
          'ch_left' => 80,
          'ch_top' => 50,
          'ch_width' => 500,
          'ch_height' => 250,
        );
      }
      $billing_date = strtotime(date('Y-m-d') . "- 7 days");
      $billing_date = date('d-m-Y', $billing_date);
      $block['subject'] = "Return Value % ($billing_date Billing)";
      $data = leanbox_dashboard_chart_query_details('delivery', $billing_date, $billing_date);

      $filter_form = drupal_render(drupal_get_form('leanbox_dashboard_chart_filter_delivery_form'));
      $block['content'] = array(
        '#markup' => theme('leanbox_dashboard', array('data' => $filter_form)),
        '#attached' => array(
          'js' => array(
            array(
              'type' => 'external',
              'data' => 'https://www.gstatic.com/charts/loader.js'
            ),
            drupal_get_path('module', 'leanbox_dashboard') . '/js/leanbox_dashboard_delivery.js',
            array(
              'data' => array('leanbox_dashboard' => array('delivery' => $data, 'area_definition' => $area_definition)),
              'type' => 'setting'
            ),
          ),
        ),
      );
      break;

    case 'party_packing_productivity':

      if (arg(1) == 'party_packing_productivity') {
        $area_definition = array(
          'width' => 700,
          'height' => 400,
          'ch_left' => 80,
          'ch_top' => 50,
          'ch_width' => 500,
          'ch_height' => 250,
        );
      }

      $loading_date = date('d-m-Y');
      $block['subject'] = "Party Packing Productivity ($loading_date Loading)";
      $data = leanbox_dashboard_chart_query_details('party_packing_productivity');
      $filter_form = drupal_render(drupal_get_form('leanbox_dashboard_chart_filter_partypack_productivity_form'));
      $block['content'] = array(
        '#markup' => theme('leanbox_dashboard', array('data' => $filter_form, 'otif_table' => $data['table'])),
        '#attached' => array(
          'js' => array(
            array(
              'type' => 'external',
              'data' => 'https://www.gstatic.com/charts/loader.js'
            ),
            drupal_get_path('module', 'leanbox_dashboard') . '/js/leanbox_dashboard_partypackingproductivitychart.js',
            array(
              'data' => array('leanbox_dashboard' => array('party_packing_productivity' => $data['output'], 'area_definition' => $area_definition)),
              'type' => 'setting'
            ),
          ),
        ),
      );
      break;

    case 'picking_productivity':

      if (arg(1) == 'picking_productivity') {
        $area_definition = array(
          'width' => 700,
          'height' => 400,
          'ch_left' => 80,
          'ch_top' => 50,
          'ch_width' => 500,
          'ch_height' => 250,
        );
      }

      $loading_date = date('d-m-Y');
      $block['subject'] = "Picking Productivity ($loading_date Loading)";
      $data = leanbox_dashboard_chart_query_details('picking_productivity');
      $filter_form = drupal_render(drupal_get_form('leanbox_dashboard_chart_filter_picking_productivity_form'));
      $block['content'] = array(
        '#markup' => theme('leanbox_dashboard', array('data' => $filter_form, 'otif_table' => $data['table'])),
        '#attached' => array(
          'js' => array(
            array(
              'type' => 'external',
              'data' => 'https://www.gstatic.com/charts/loader.js'
            ),
            drupal_get_path('module', 'leanbox_dashboard') . '/js/leanbox_dashboard_pickingproductivitychart.js',
            array(
              'data' => array('leanbox_dashboard' => array('picking_productivity' => $data['output'], 'area_definition' => $area_definition)),
              'type' => 'setting'
            ),
          ),
        ),
      );
      break;

    case 'bill_pendency':

      if (arg(1) == 'bill_pendency') {
        $area_definition = array(
          'width' => 700,
          'height' => 400,
          'ch_left' => 80,
          'ch_top' => 50,
          'ch_width' => 500,
          'ch_height' => 250,
        );
      }

      $loading_date = date('d-m-Y', strtotime("-1 days"));
      $block['subject'] = "Bill Pendency ($loading_date Billing)";
      $data = leanbox_dashboard_chart_query_details('bill_pendency', $loading_date, $loading_date);
      $filter_form = drupal_render(drupal_get_form('leanbox_dashboard_chart_filter_bill_pendency_form'));
      $block['content'] = array(
        '#markup' => theme('leanbox_dashboard', array('data' => $filter_form, 'otif_table' => $data['table'])),
        '#attached' => array(
          'js' => array(
            array(
              'type' => 'external',
              'data' => 'https://www.gstatic.com/charts/loader.js'
            ),
            drupal_get_path('module', 'leanbox_dashboard') . '/js/leanbox_dashboard_bill_pendencychart.js',
            array(
              'data' => array('leanbox_dashboard' => array('bill_pendency' => $data['output'], 'area_definition' => $area_definition)),
              'type' => 'setting'
            ),
          ),
        ),
      );
      break;

    case 'otif':

      $bill_date = leanbox_dashboard_get_default_pdd_date_for_chart();
      $bill_date = date('d-m-Y', $bill_date);
      $block['subject'] = "OTIF Value ($bill_date Billing)";
      $data = leanbox_dashboard_gauge_chart_query_details('otif');

      $filter_form = drupal_render(drupal_get_form('leanbox_dashboard_chart_filter_otif_form'));
      $block['content'] = array(
        '#markup' => theme('leanbox_dashboard', array('data' => $filter_form, 'otif_table' => $data['table'],)),
        '#attached' => array(
          'js' => array(
            array(
              'type' => 'external',
              'data' => 'https://www.gstatic.com/charts/loader.js'
            ),
            drupal_get_path('module', 'leanbox_dashboard') . '/js/leanbox_dashboard_otifchart.js',
            array(
              'data' => array('leanbox_dashboard' => array('otif' => $data['output'],)),
              'type' => 'setting'
            ),
          ),
        ),
      );
      break;
    
    case 'otif_trends':
      
        if (arg(1) == 'otif_trends') {
        $area_definition = array(
          'width' => 700,
          'height' => 400,
          'ch_left' => 80,
          'ch_top' => 50,
          'ch_width' => 500,
          'ch_height' => 250,
        );
      }

      $bill_date = leanbox_dashboard_get_default_pdd_date_for_chart();
      $bill_date = date('d-m-Y', $bill_date);
      $block['subject'] = "OTIF Day Wise ($bill_date Billing)";
      $data = leanbox_dashboard_otif_trends_chart_query_details('otif_trends');

      $filter_form = drupal_render(drupal_get_form('leanbox_dashboard_chart_filter_otif_trends_form'));
      $block['content'] = array(
        '#markup' => theme('leanbox_dashboard', array('data' => $filter_form, 'otif_table' => $data['table'],)),
        '#attached' => array(
          'js' => array(
            array(
              'type' => 'external',
              'data' => 'https://www.gstatic.com/charts/loader.js'
            ),
            drupal_get_path('module', 'leanbox_dashboard') . '/js/leanbox_dashboard_otif_trends_chart.js',
            array(
              'data' => array('leanbox_dashboard' => array('otif_trends' => $data['output'], 'area_definition' => $area_definition)),
              'type' => 'setting'
            ),
          ),
        ),
      );
      break;

    case 'bills_per_person':

      if (arg(1) == 'bills_per_person') {
        $area_definition = array(
          'width' => 700,
          'height' => 400,
          'ch_left' => 80,
          'ch_top' => 50,
          'ch_width' => 500,
          'ch_height' => 250,
        );
      }

      $loading_date = date('d-m-Y');
      $block['subject'] = "Bills Per Person ($loading_date Dispatch)";
      $data = leanbox_dashboard_chart_query_details('bills_per_person');
      $filter_form = drupal_render(drupal_get_form('leanbox_dashboard_chart_filter_billsperperson_form'));
      $block['content'] = array(
        '#markup' => theme('leanbox_dashboard', array('data' => $filter_form)),
        '#attached' => array(
          'js' => array(
            array(
              'type' => 'external',
              'data' => 'https://www.gstatic.com/charts/loader.js'
            ),
            drupal_get_path('module', 'leanbox_dashboard') . '/js/leanbox_dashboard_billsperpersonchart.js',
            array(
              'data' => array('leanbox_dashboard' => array('bills_per_person' => $data, 'area_definition' => $area_definition)),
              'type' => 'setting'
            ),
          ),
        ),
      );
      break;


    case 'bills_per_van':

      if (arg(1) == 'bills_per_van') {
        $area_definition = array(
          'width' => 700,
          'height' => 400,
          'ch_left' => 80,
          'ch_top' => 50,
          'ch_width' => 500,
          'ch_height' => 250,
        );
      }

      $loading_date = date('d-m-Y');
      $block['subject'] = "Bills Per Van ($loading_date Loading)";
      $data = leanbox_dashboard_chart_query_details('bills_per_van');
      $filter_form = drupal_render(drupal_get_form('leanbox_dashboard_chart_filter_billspervan_form'));
      $block['content'] = array(
        '#markup' => theme('leanbox_dashboard', array('data' => $filter_form)),
        '#attached' => array(
          'js' => array(
            array(
              'type' => 'external',
              'data' => 'https://www.gstatic.com/charts/loader.js'
            ),
            drupal_get_path('module', 'leanbox_dashboard') . '/js/leanbox_dashboard_billspervanchart.js',
            array(
              'data' => array('leanbox_dashboard' => array('bills_per_van' => $data, 'area_definition' => $area_definition)),
              'type' => 'setting'
            ),
          ),
        ),
      );
      break;

    case 'pp_ota':

      if (arg(1) == 'pp_ota') {
        $area_definition = array(
          'width' => 700,
          'height' => 400,
          'ch_left' => 80,
          'ch_top' => 50,
          'ch_width' => 500,
          'ch_height' => 250,
        );
      }

      $loading_date = date('d-m-Y');
      $block['subject'] = "Party Packing On Time Adherence ($loading_date Loading)";
      $data = leanbox_dashboard_chart_query_details('pp_ota');
      $filter_form = drupal_render(drupal_get_form('leanbox_dashboard_chart_filter_pp_ota_form'));
      $block['content'] = array(
        '#markup' => theme('leanbox_dashboard', array('data' => $filter_form)),
        '#attached' => array(
          'js' => array(
            array(
              'type' => 'external',
              'data' => 'https://www.gstatic.com/charts/loader.js'
            ),
            drupal_get_path('module', 'leanbox_dashboard') . '/js/leanbox_dashboard_pp_ota.js',
            array(
              'data' => array('leanbox_dashboard' => array('pp_ota' => $data, 'area_definition' => $area_definition)),
              'type' => 'setting'
            ),
          ),
        ),
      );
      break;

    case 'picking_ota':

      if (arg(1) == 'picking_ota') {
        $area_definition = array(
          'width' => 700,
          'height' => 400,
          'ch_left' => 80,
          'ch_top' => 50,
          'ch_width' => 500,
          'ch_height' => 250,
        );
      }

      $loading_date = date('d-m-Y');
      $block['subject'] = "Picking On Time Adherence VAN Loose ($loading_date Loading)";
      $data = leanbox_dashboard_chart_query_details('picking_ota');
      $filter_form = drupal_render(drupal_get_form('leanbox_dashboard_chart_filter_picking_ota_form'));
      $block['content'] = array(
        '#markup' => theme('leanbox_dashboard', array('data' => $filter_form)),
        '#attached' => array(
          'js' => array(
            array(
              'type' => 'external',
              'data' => 'https://www.gstatic.com/charts/loader.js'
            ),
            drupal_get_path('module', 'leanbox_dashboard') . '/js/leanbox_dashboard_picking_ota.js',
            array(
              'data' => array('leanbox_dashboard' => array('picking_ota' => $data, 'area_definition' => $area_definition)),
              'type' => 'setting'
            ),
          ),
        ),
      );
      break;

    case 'unloading_ota':

      if (arg(1) == 'unloading_ota') {
        $area_definition = array(
          'width' => 700,
          'height' => 400,
          'ch_left' => 80,
          'ch_top' => 50,
          'ch_width' => 500,
          'ch_height' => 250,
        );
      }

      $loading_date = date('d-m-Y');
      $block['subject'] = "Unloading On Time Adherence ($loading_date EGIR)";
      $data = leanbox_dashboard_chart_query_details('unloading_ota');
      $filter_form = drupal_render(drupal_get_form('leanbox_dashboard_chart_filter_unloading_ota_form'));
      $block['content'] = array(
        '#markup' => theme('leanbox_dashboard', array('data' => $filter_form)),
        '#attached' => array(
          'js' => array(
            array(
              'type' => 'external',
              'data' => 'https://www.gstatic.com/charts/loader.js'
            ),
            drupal_get_path('module', 'leanbox_dashboard') . '/js/leanbox_dashboard_unloading_ota.js',
            array(
              'data' => array('leanbox_dashboard' => array('unloading_ota' => $data, 'area_definition' => $area_definition)),
              'type' => 'setting'
            ),
          ),
        ),
      );
      break;

    case 'dispatch_ota':

      if (arg(1) == 'dispatch_ota') {
        $area_definition = array(
          'width' => 700,
          'height' => 400,
          'ch_left' => 80,
          'ch_top' => 50,
          'ch_width' => 500,
          'ch_height' => 250,
        );
      }

      $loading_date = date('d-m-Y');
      $block['subject'] = "Dispatch On Time Adherence ($loading_date Dispatch)";
      $data = leanbox_dashboard_chart_query_details('dispatch_ota');
      $filter_form = drupal_render(drupal_get_form('leanbox_dashboard_chart_filter_dispatch_ota_form'));
      $block['content'] = array(
        '#markup' => theme('leanbox_dashboard', array('data' => $filter_form)),
        '#attached' => array(
          'js' => array(
            array(
              'type' => 'external',
              'data' => 'https://www.gstatic.com/charts/loader.js'
            ),
            drupal_get_path('module', 'leanbox_dashboard') . '/js/leanbox_dashboard_dispatch_ota.js',
            array(
              'data' => array('leanbox_dashboard' => array('dispatch_ota' => $data, 'area_definition' => $area_definition)),
              'type' => 'setting'
            ),
          ),
        ),
      );
      break;

    case 'outlet_status':

      $loading_date = date('d-m-Y');
      $block['subject'] = "Outlet Status";
      $data = leanbox_dashboard_chart_query_details('outlet_status');
      $block['content'] = array(
        '#markup' => theme('leanbox_dashboard', array('data' => $data)),
      );
      break;
  }

  return $block;
}

/**
 * Implements hook_theme
 */
function leanbox_dashboard_theme() {
  return array(
    'leanbox_dashboard' => array(
      'template' => 'leanbox-dashboard',
      'variables' => array('data' => NULL, 'otif_table' => NULL),
    ),
  );
}

/**
 * Implements hook_preprocess_page
 * @param type $vars
 */
function leanbox_dashboard_preprocess_page(&$vars) {
  $arg = drupal_get_path_alias();
  if ($arg == 'dashboard') {
    drupal_add_js(drupal_get_path('module', 'leanbox_dashboard') . '/js/leanbox_dashboard.js');
  }
}

function leanbox_dashboard_get_areahookgroup_entity($title, $day_tid) {
  $query = db_select('node', 'n');
  $query->addTag('node_uid');
  $query->condition('n.type', 'area_hook_master');
  $query->join('field_data_field_area_hook_day', 'a', 'a.entity_id = n.nid');
  $query->leftjoin('field_data_field_area_hook_group', 'g', 'g.entity_id = n.nid');

  $query->condition('a.field_area_hook_day_tid', $day_tid);
  $query->condition('n.title', $title);
  $query->fields('g', array('field_area_hook_group_value'));
  $query->fields('n', array('nid'));
  $output = $query->execute()->fetch(PDO::FETCH_ASSOC); // list of all area hook
  return $output;
}

function leanbox_dashboard_target_value_using_voc_name($vname) {
  $uid = $GLOBALS['user']->uid;
  $distributor_id = change_feeds_import_get_distributor_id($uid);
  $query1 = db_select('node', 'n');
  $query1->leftjoin('field_data_field_dets_bulk', 'v', 'v.entity_id = n.nid');
  $query1->leftjoin('field_data_field_dets_loose', 'l', 'v.entity_id = n.nid');
  $query1->leftjoin('field_data_field_fnb_bulk', 'fv', 'fv.entity_id = n.nid');
  $query1->leftjoin('field_data_field_fnb_loose', 'fl', 'fl.entity_id = n.nid');
  $query1->leftjoin('field_data_field_non_pp', 'np', 'np.entity_id = n.nid');
  $query1->leftjoin('field_data_field_pp', 'pp', 'pp.entity_id = n.nid');
  $query1->leftjoin('field_data_field_pp_bulk', 'pb', 'pb.entity_id = n.nid');
  $query1->leftjoin('field_data_field_pp_loose', 'pl', 'pl.entity_id = n.nid');
  $query1->fields('v', array('field_dets_bulk_value'));
  $query1->fields('l', array('field_dets_loose_value'));
  $query1->fields('fv', array('field_fnb_bulk_value'));
  $query1->fields('fl', array('field_fnb_loose_value'));
  $query1->fields('np', array('field_non_pp_value'));
  $query1->fields('pp', array('field_pp_value'));
  $query1->fields('pb', array('field_pp_bulk_value'));
  $query1->fields('pl', array('field_pp_loose_value'));
  $query1->condition('n.uid', $distributor_id);
  $query1->condition('n.type', 'van_stop_master');
  $res = $query1->execute()->fetch(PDO::FETCH_ASSOC);

  $target['dets bulk'] = $res['field_dets_bulk_value'];
  $target['dets loose'] = $res['field_dets_loose_value'];
  $target['fnb bulk'] = $res['field_fnb_bulk_value'];
  $target['fnb loose'] = $res['field_fnb_loose_value'];
  $target['NON-PP'] = $res['field_non_pp_value'];
  $target['PP'] = $res['field_pp_value'];
  $target['pp bulk'] = $res['field_pp_bulk_value'];
  $target['pp loose'] = $res['field_pp_loose_value'];

  return $target;
}

/**
 * 
 * @param type $vname
 * @return array
 */
function leanbox_dashboard_all_value_using_voc_name($vname) {
  $query1 = db_select('taxonomy_term_data', 't');
  $query1->join('taxonomy_vocabulary', 'v', 'v.vid = t.vid');
  $query1->condition('v.name', $vname);
  $query1->fields('t', array('tid', 'name'));
  $target = $query1->execute()->fetchAllKeyed(0, 1);
  return $target;
}