<?php
/**
 * VehicleTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Route Optimization API
 *
 * Our Route Optimization API solves the so called vehicle routing problem fast. It calculates an optimal tour for a set of vehicles, services and constraints
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * VehicleTest Class Doc Comment
 *
 * @category    Class */
// * @description Vehicle
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class VehicleTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "Vehicle"
     */
    public function testVehicle()
    {

    }

    /**
     * Test attribute "vehicle_id"
     */
    public function testPropertyVehicleId()
    {

    }

    /**
     * Test attribute "type_id"
     */
    public function testPropertyTypeId()
    {

    }

    /**
     * Test attribute "start_address"
     */
    public function testPropertyStartAddress()
    {

    }

    /**
     * Test attribute "end_address"
     */
    public function testPropertyEndAddress()
    {

    }

    /**
     * Test attribute "break"
     */
    public function testPropertyBreak()
    {

    }

    /**
     * Test attribute "return_to_depot"
     */
    public function testPropertyReturnToDepot()
    {

    }

    /**
     * Test attribute "earliest_start"
     */
    public function testPropertyEarliestStart()
    {

    }

    /**
     * Test attribute "latest_end"
     */
    public function testPropertyLatestEnd()
    {

    }

    /**
     * Test attribute "skills"
     */
    public function testPropertySkills()
    {

    }

}
